### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by daiyulejia** [Yarkona/TOF#1]
您好，您给的数据集解压缩出现问题，解压缩的数据集里面好像没有twitter_ner这个文件夹，好像也没有raw2bio.py.您可以把完整数据集再发一吗？

**Comment by Yarkona** [comment]
您好，原来的数据集我在linux上解压没有出现问题，但在windows和mac似乎不太行。具体原因我还没有找到。twitter_ner数据集已经上传到这个链接了https://drive.google.com/file/d/1ZgH17y2lJrtv0QC9oFkcQjq0msd-YRN2/view?usp=sharing。 如果需要其他数据集，可以提供下数据集名称。

**Comment by daiyulejia** [comment]
cross-domain、cross-lingual、translate/Cross-lingual_NER-master我按照里面的网址下载下来之后都打不开，再linux上解压缩也是显示归档EOF问题

**Comment by daiyulejia** [comment]
可以把这三个文件都给我发一份吗，谢谢

**Comment by Yarkona** [comment]
数据集链接已经更新～
