### ISSUE TITLE
Dataset for source domain MRC

### ISSUE THREAD

**Issue by mtt1998** [Yarkona/TOF#2]
Hi,
     Thank you for sharing the code ! I am curious about which MRC dataset is used for source domain. For example, if we want to transfer from CoNLL03 to CBS SciTech News, the NewsQA dataset is used for target scitech news domain, but which MRC dataset used for CoNLL03 domain ?

**Comment by Yarkona** [comment]
We use SQuAD as the MRC dataset for source domain, and sample 10k examples as the training data for fine-tuning.
